### ISSUE TITLE
Patch SolR's log4j

### ISSUE THREAD

**Issue by florianm** [ckan/ckan-solr#3]
According to [the SolR docs](https://solr.apache.org/guide/8_0/configuring-logging.html), SolR 8.0 (used in CKAN 2.9+) uses [Log4J 2.11.0](https://logging.apache.org/log4j/log4j-2.11.0/) which is impacted by [CVE-2021-44228](https://logging.apache.org/log4j/2.x/security.html).

Is the current CKAN setup vulnerable to this CVE?

**Comment by wood-chris** [comment]
Hi @florianm - I did a bit of digging around this today. The debian packages `solr-jetty` (the package recommended by CKAN - https://packages.ubuntu.com/focal/solr-jetty) and `solr-tomcat` both appear to include a _really_ old version of solr: 3.6.2 (released in 2012), with some core security updates applied since then. 

I'm sure there's a good reason why `solr-jetty` _does_ include a much more recent version of jetty (from 2020), but I'm not sure I can think why 🤷

**Comment by amercader** [comment]
@florianm @wood-chris Please see here for all info on Log4J2 / Solr and CKAN:

https://github.com/ckan/ckan/discussions/6596

TL;DR: pull the latest images and you should be fine
